name: Backup automático do repositório

on:
  schedule:
    - cron: '0 1 * * *' # todos os dias às 01:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório (mirror)
        run: |
          git clone --mirror https://x-access-token:${{ secrets.BACKUP_TOKEN }}@github.com/riddle022/comecce.git

      - name: Enviar backup para repositório destino
        run: |
          cd comece.git
          git push --mirror https://x-access-token:${{ secrets.BACKUP_TOKEN }}@github.com/riddle022/comecce-backup.git
